home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /
actu_article:
    resource: "@ActuArticleBundle/Resources/config/routing.yml"
    prefix:   /articles
actu_category:
    resource: "@ActuCategoryBundle/Resources/config/routing.yml"
    prefix:   /articles/categories


    





